spring.application.name: spring-boot-admin

management.endpoints.web.exposure:
  include: "*"

spring.cloud.kubernetes.discovery:
  all-namespaces: true
  service-labels:
    spring-boot: "true"
  include-not-ready-addresses: true
